# Generated by Django 3.2 on 2023-03-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('product', '0002_auto_20230203_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniproduct',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.productimage'),
        ),
    ]
