# Generated by Django 3.2 on 2022-11-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221123_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='included',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='miniproduct',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uuid',
            new_name='id',
        ),
    ]
