# Generated by Django 3.2 on 2022-07-09 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220709_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='included',
            options={'verbose_name': 'Include', 'verbose_name_plural': 'Includes'},
        ),
        migrations.AlterField(
            model_name='included',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
