# Generated by Django 3.2 on 2022-07-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20220709_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Included',
        ),
    ]
