# Generated by Django 3.2 on 2022-07-09 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_delete_included'),
    ]

    operations = [
        migrations.CreateModel(
            name='Included',
            fields=[
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.CharField(max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='product.product')),
            ],
            options={
                'verbose_name': 'Include',
                'verbose_name_plural': 'Includes',
            },
        ),
    ]
