# Generated by Django 3.2 on 2022-07-10 13:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20220710_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_images', to='product.image')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='others',
            field=models.ManyToManyField(limit_choices_to=3, related_name='others', to='product.MiniProduct'),
        ),
    ]
