# Generated by Django 3.2 on 2022-07-11 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('product', '0018_auto_20220710_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='first',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first', to='images.productimage'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='second',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='images.productimage'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='third',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='images.productimage'),
        ),
        migrations.AlterField(
            model_name='miniproduct',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_images', to='images.productimage'),
        ),
        migrations.AlterField(
            model_name='miniproduct',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.productimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='others',
            field=models.ManyToManyField(blank=True, related_name='others', to='product.MiniProduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
