# Generated by Django 3.2 on 2022-07-11 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20220711_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
