# Generated by Django 3.2 on 2022-07-11 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_categoryimage'),
        ('product', '0020_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_image', to='images.categoryimage'),
        ),
    ]
