# Generated by Django 3.2 on 2022-07-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='orderNumber',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
