# Generated by Django 3.2 on 2022-10-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_category_ordernumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['orderNumber'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
