# Generated by Django 3.2 on 2022-11-23 06:38

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to=images.models.category_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=100, null=True)),
                ('desktop', models.ImageField(upload_to=images.models.product_directory_path, verbose_name='Desktop Image')),
                ('tablet', models.ImageField(upload_to=images.models.product_directory_path, verbose_name='Tablet Image')),
                ('mobile', models.ImageField(upload_to=images.models.product_directory_path, verbose_name='Mobile Image')),
            ],
        ),
    ]
