# Generated by Django 3.2 on 2022-07-11 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_categoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimage',
            old_name='desktop',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='categoryimage',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='categoryimage',
            name='tablet',
        ),
    ]
