# Generated by Django 3.2 on 2022-11-23 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20221123_0453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimage',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='uuid',
            new_name='id',
        ),
    ]
