# Generated by Django 3.2 on 2023-02-27 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230203_1220'),
        ('images', '0001_initial'),
        ('home', '0002_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.TextField(blank=True, null=True)),
                ('box_type', models.CharField(choices=[('big', 'Big'), ('normal', 'Normal'), ('broken', 'Broken')], default='normal', max_length=100)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.productimage')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
