# Generated by Django 3.2 on 2022-10-23 03:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0023_alter_category_options'),
        ('cart', '0002_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product_id', 'owner_id')},
        ),
    ]
